applitools/eyes.sdk.javascript1

eyes.sdk.core.javascript/src/UserAgent.js
This is clearly a typo - not only is `i` not defined in the scope of this line, but it needs to use the edge regex directly, not look it up in list of all browser regexes.
Without this, you can't test MS Edge with webdriverio!
=> Allow Edge testing with webdriverio

eyes.sdk.core/lib/server/ServerConnector.js
While working on cypress sdk there is a need to get render status based on renderId and not necessarily on running render instance
=> API to get render status by renderId

eyes.sdk.core/lib/renderer/RenderStatusResults.js, eyes.sdk.core/lib/server/ServerConnector.js, eyes.sdk.core/package-lock.json, eyes.sdk.core/package.json, eyes.sdk.core/test/unit/RenderStatusResults.spec.js, eyes.sdk.core/test/unit/TestResults.spec.js
Rendering grid now sends `OS` and `userAgent` as part of `/render-status` response.
This PR populates the result with these values
=> Add OS and userAgent to RenderStatusResults

eyes.sdk.core/lib/utils/GeneralUtils.js, eyes.sdk.core/test/unit/utils/GeneralUtils.spec.js
Added support for:
- plain objects (currently show as [object Object])
- errors (to show stack trace)
- functions (to show full body)
=> Improve GeneralUtils.stringify

eyes.sdk.core/lib/EyesBase.js, eyes.sdk.core/lib/match/AppOutput.js
We're doing a PoC in showing relevant DOM information in the Eyes app.
To this end, we upload the information to the Eyes server, then sending it as a parameter called `domUrl` inside `MatchWindowData`.
The current implementation puts `domUrl` inside the `AppOutput` object. I figured that was the most proper place to put it.
I thing I have doubts about is in `_getAppOutputWithScreenshot` in `EyesBase.js`. This method is a bit hard to read, and so I didn't find an easy way to add this functionality there. I tried to be consistent with the other params like `screenshotUrl`. Also, there aren't tests for this method and I didn't want to dive into starting a new test for `EyesBase`. Any suggestion on how to do this better is welcome.
The SDK that currently sends this information is the Cypress …
=> Support sending domUrl in matchWindow

eyes.sdk.core/lib/server/ServerConnector.js
small addition to log - when renderStatus returns it's helpful to see what renderId it belongs to.
=> Add log for renderId in renderStatus response

eyes.sdk.core/lib/renderer/RenderInfo.js, eyes.sdk.core/lib/utils/GeneralUtils.js, eyes.sdk.core/test/unit/RenderInfo.spec.js, eyes.sdk.core/test/unit/utils/GeneralUtils.spec.js
Rendering grid now supports 2 additional `sizeMode`'s:
1) 'selector' - with an additional `selector` property inside `RenderInfo`.
2) 'region' - with an additional `region` property that conforms to the `Region` class.
This PR adds these 2 properties to `RenderInfo` so they can be sent to the rendering grid.
I also suggest (not in this PR) to deprecate RenderInfo.fromRectangleSize because it's not scalable when additional arguments add up (like selector and region).
=> Support selector and region in RenderInfo

eyes.sdk.core/lib/server/ServerConnector.js
Axios hangs when called with POST/PUT and an empty buffer as data.
Issue was submitted here:
https://github.com/axios/axios/issues/1701
This PR is a workaround until they fix the issue (or we switch http client).
=> Fix axios issue with empty buffer

eyes.sdk.core/index.js, eyes.sdk.core/lib/renderer/EmulationDevice.js, eyes.sdk.core/lib/renderer/EmulationInfo.js, eyes.sdk.core/lib/renderer/RenderInfo.js, eyes.sdk.core/lib/renderer/RenderRequest.js, eyes.sdk.core/lib/renderer/ScreenOrientation.js, eyes.sdk.core/test/unit/EmulationDevice.spec.js, eyes.sdk.core/test/unit/EmulationInfo.spec.js, eyes.sdk.core/test/unit/RenderInfo.spec.js, eyes.sdk.core/test/unit/RenderRequest.spec.js
This PR adds emulation info to RenderRequest, as documented in the rendering grid API [here](https://docs.google.com/document/d/1B1OtmNqJ7G7I6iedqYK3PwKC5_1ah_1uo9Kc_X8O858/edit#).
For code style consistency I created the EmuationInfo and EmulationDevice classes, plus ScreenOrientation enum.
Tests for these classes were added too.
=> Add emulation info to render request

eyes.sdk.core/lib/renderer/RenderStatusResults.js, eyes.sdk.core/test/unit/RenderStatusResults.spec.js
To accommodate device emulation, it's possible to pass `emulationInfo` with `deviceName` to the visual grid. In this case, the viewport size is determined by the visual grid, so it is returned in the render-status response.
This PR adds `width` and `height` properties to `RenderStatusResults`.
=> Add width and height to RenderStatusResults

eyes.sdk.core/lib/renderer/RenderStatusResults.js, eyes.sdk.core/test/unit/RenderInfo.spec.js, eyes.sdk.core/test/unit/RenderStatusResults.spec.js
Rendering grid takes a dom capture and uploads to eyes server, then provides the uploaded URL in the response of `/render-status` when the image is rendered.
Rendering grid protocol doc:
https://docs.google.com/document/d/1B1OtmNqJ7G7I6iedqYK3PwKC5_1ah_1uo9Kc_X8O858/edit#
=> Add domLocation to RenderStatusResults

eyes.sdk.core/lib/EyesBase.js, eyes.sdk.core/lib/match/AppOutput.js, eyes.sdk.core/lib/renderer/RenderRequest.js, eyes.sdk.core/lib/renderer/RenderStatusResults.js, eyes.sdk.core/test/unit/RenderRequest.spec.js, eyes.sdk.core/test/unit/RenderStatusResults.spec.js
When taking a screenshot of a region using the visual-grid, the relative offset of the image is reported back from the visual-grid and should be uploaded as part of the `AppOutput` object on the image.
This PR adds the necessary properties to the visual-grid's API objects `RenderRequest` and `RenderStatusResults` including tests, and adds `imageLocation` as part of `AppOutput` sent in `matchWindow`.
See the visual-grid's API for `selectorsToFindRegionsFor` and `selectorRegions` here:
https://docs.google.com/document/d/1B1OtmNqJ7G7I6iedqYK3PwKC5_1ah_1uo9Kc_X8O858/edit#
=> Add location info for image in checkRegion

eyes.sdk.core/lib/renderer/RenderRequest.js, eyes.sdk.core/test/unit/RenderRequest.spec.js
The `sendDom` flag provides the ability to enable/disable DOM snapshot capturing in the rendering grid.
*breaking change*: changing RenderRequest arguments to a single destructured object
=> add sendDom flag to RenderRequest and separate resources from DOM

eyes.sdk.core/lib/renderer/RGridResource.js
The rendering-grid needs to know the content-type of iframe resources.
This PR adds content-type to all resources. There's a bit redundancy in that only `x-applitools-cdt/html` content-type needs to be sent, but this can be done later if we find it's necessary.
=> Add contentType to resource in renderRequest

packages/eyes-sdk-core/lib/AppEnvironment.js, packages/eyes-sdk-core/lib/EyesBase.js, packages/eyes-sdk-core/lib/renderer/RenderRequest.js
We lost this feature in Cypress and Storybook after the `visual-grid-client` updated to `eyes-sdk-core` v4.
It was added to v2.0.1 not through git :(
=> Support deviceInfo, hostAppInfo, hostOSInfo

packages/eyes-sdk-core/lib/server/ServerConnector.js
when the rendering grid doesn't have a job for a certain renderId yet, and gets a request for status, it returns null (since it doesn't have any info about it).
This PR aims to handle this situation
=> handle null render status result

packages/eyes-common/lib/utils/GeneralUtils.js, packages/eyes-common/test/unit/utils/GeneralUtils.spec.js
for doing :
getPropertyByPath(obj, "user.name.email") // return undefined or value - no exceptions
* this is instead of doing: obj && obj.user && obj.user.email && obj.user.address ..
=> Added general util function to get property of object by path

packages/visual-grid-client/package.json, packages/visual-grid-client/src/sdk/createRenderRequests.js, packages/visual-grid-client/src/sdk/takeScreenshot.js, packages/visual-grid-client/src/visual-grid-client.js, packages/visual-grid-client/test/e2e/takeScreenshot.e2e.test.js
This is to support the vscode extension. VGC now exports an async function that takes a screenshot.
e.g.
```
const {takeScreenshot} = require('@applitools/visual-grid-client')
```
Minor version already published
=> Export function takeScreenshot

packages/eyes-sdk-core/lib/TestResults.js, packages/eyes-sdk-core/test/unit/TestResults.spec.js, packages/visual-grid-client/test/it/testWindow.it.test.js
Fix wrong behavior of StepInfo constructor.
I have a question about should `apiUrls` be stringified when we call `toString` method?
In the current implementation, it is stringified, so I update tests as well.
=> set apiUrls to step info instance in constructor

packages/dom-capture/src/browser/captureFrame.js, packages/dom-capture/src/browser/fetchCss.js, packages/dom-capture/tests/captureFrame.test.js, packages/dom-capture/tests/fixtures/longCss.dom.json, packages/dom-capture/tests/fixtures/longCss.html, packages/dom-capture/tests/util/testServer.js
Add time-limit for fetches to the `captureFrame`. I used `AbortController` to abort the request and combinate it with `Promise.race()` in case request will not be aborted (this bug exists in Safari browser)
=> Add fetch time limit

packages/sdk-test-kit/package.json, packages/sdk-test-kit/src/coverage-tests/cli-util.js, packages/sdk-test-kit/test/coverage-tests/cli-util.spec.js, yarn.lock
Currently, running the following will result in 12 executions:
```
npx coverage-tests run --fn TestCheckRegion --fm isScrollStitching
```
(It's essentially `*TestCheckRegion*`)
With this PR, it will result in 1 execution, which is the desired state (otherwise there's no way to just run TestCheckRegion except by index which is not user friendly).
=> Test kit: ability to filter by name with glob pattern

packages/eyes-webdriverio-4/package.json, packages/sdk-coverage-tests/src/cli.js, packages/sdk-coverage-tests/src/cli/cli-util.js, packages/sdk-coverage-tests/src/cli/commands/create-tests.js, packages/sdk-coverage-tests/src/code-export/emit.js
Here I added an `--all` for ignoring the `disabled` flag on supported tests.
I have a question in addition. Why the filtering out of disabled tests is not a part of `filterTests` function? Does it have some reason?
=> coverage-tests: `--all` flag

packages/eyes-sdk-core/lib/metadata/StartInfo.js
Instead of doing something like this:
```javascript
matchSingleWindowData._startInfo._displayName = displayName;
```
=> startInfo-displayName-support

package.json, packages/sdk-coverage-tests/src/report/index.js, packages/sdk-coverage-tests/src/report/xml.js
it junit report have a <testsutes> tag it was parsed to the array of the arrays instead of array of the testcases.
For the report with a structure 
```
<testsuites>
<testsuite>
<testcase>
</testcase>
</testsuite>
<testsuite>
<testcase>
</testcase>
</testsuite>
</testsuites>
```
process-report command is failed with an error "Cannot read property 'name' of undefined"
Parsing such junit reports is required for the some SDKs.
=> update xml parsing for sdk-coverage-tests package

packages/sdk-coverage-tests/src/report/xml.js, packages/sdk-coverage-tests/test/report/fixtures/multiple-suites-multiple-tests-each.xml, packages/sdk-coverage-tests/test/report/fixtures/multiple-suites-multiple-tests-one.xml, packages/sdk-coverage-tests/test/report/index.spec.js
fixed error when there are many testcases in one testsuite inside testsuites tag. Which wasn't properly covered earlier. 
ex:
```
<testsuites>
<testsuite>
<testcase/>
<testcase/>
</testsuite>
</testsuites>
```
added testcases for the coverage-tool parser
=> update to xml parser

packages/eyes-sdk-core/index.js, packages/eyes-sdk-core/lib/config/ProxySettings.js, packages/eyes-sdk-core/lib/server/getTunnelAgentFromProxy.js, packages/eyes-sdk-core/lib/server/requestHelpers.js, packages/visual-grid-client/src/sdk/checkWindow.js, packages/visual-grid-client/src/sdk/createRGridDOMAndGetResourceMapping.js, packages/visual-grid-client/src/sdk/getAllResources.js, packages/visual-grid-client/src/sdk/getFetchOptions.js, packages/visual-grid-client/test/unit/sdk/getFetchOptions.test.js, packages/visual-grid-client/test/util/FakeEyesWrapper.js
Currently we have 2 network libraries: `axios` and `node-fetch`. This is not ideal, but to change it would be risky and well thought.
In the meantime, we have an issue where the user specified a proxy with `isHttpOnly` and a tunnel was not created for `node-fetch`.
The better solution is to use https://github.com/TooTallNate/node-http-proxy-agent or https://github.com/TooTallNate/node-https-proxy-agent also when `isHttpOnly === false`, but the best solution would be to use only `axios` or `node-fetch` for everything.
=> Use tunnel for vg resources

packages/eyes-webdriverio-5/src/EyesService.js
When running with `wdio` and `jasmine`, `appName` and `testName` are not set. From digging into the code it appears they are in a different property.
So this PR enables a fallback to use the jasmine props if the initial ones are unset.
=> Fix for WebDriver with 'jasmine'

packages/sdk-coverage-tests/src/report/xml.js, packages/sdk-coverage-tests/test/report/fixtures/single-suite-multiple-tests-with-skipped.xml, packages/sdk-coverage-tests/test/report/fixtures/single-suite-skipped-test.xml, packages/sdk-coverage-tests/test/report/index.spec.js, yarn.lock
Updated xml parser to filter tests which have property `skipped` so they weren't sent to the dashboard 
Added the tests for the new testcases
Examples of the xml with `skipped` property added to the fixtures
=> Xml parser skipped

packages/eyes-sdk-core/CHANGELOG.md, packages/eyes-sdk-core/lib/EyesClassic.js, packages/eyes-sdk-core/lib/EyesCore.js, packages/eyes-sdk-core/lib/EyesVisualGrid.js, packages/eyes-sdk-core/lib/runner/ClassicRunner.js, packages/eyes-sdk-core/lib/runner/EyesRunner.js, packages/eyes-sdk-core/lib/server/ServerConnector.js, packages/sdk-coverage-tests/src/spec-emitter.js, packages/sdk-coverage-tests/src/supported-tests.js, packages/sdk-coverage-tests/src/tests.js
- Add `eyes.locate` API.
- Types are provided instead of fluent API or data classes.
- Generic coverage test for classic and VG.
The tricky part was to take a viewport screenshot with `EyesVisualGrid`. For that I moved all the necessary properties and methods from `EyesClassic` to `EyesCore`.
I didn't want to take it all the way to merge the Eyes classes. That's a desired refactor, but not critical ATM. So only the minimal changes were made.
The part I was forced to do and is ugly is to call `this.getAndSaveRenderingInfo` from inside `eyes.locate`, since `EyesVisualGrid` doesn't call `serverConnector.renderInfo()` - because it does everything inside VGC. Because it's cached it's not a redundant network call.
=> Support visual locators

packages/sdk-coverage-tests/src/cli.js, packages/sdk-coverage-tests/src/cli/commands/process-report.js, packages/sdk-coverage-tests/src/report/index.js, packages/sdk-coverage-tests/test/report/index.spec.js
New option reportId used for the request to the dashboard. (--reportId 'value' or -id 'value')
By default value is set to undefined, so after JSON.stringify() it's became empty and won't be sent to the server. Behaviour should be the same as it was before.
Feature required to make possible combine results from the generic and original testsuites from different languages.
=> added new customization

packages/eyes-sdk-core/lib/EyesClassic.js, packages/eyes-sdk-core/lib/EyesVisualGrid.js, packages/eyes-sdk-core/test/unit/EyesClassic.spec.js
https://trello.com/c/XAmA255U
https://trello.com/c/1Bl2EaDE
Suppose this case:
```
eyes.close(false)
```
And there was an internal error. It might be due to our bug and it might be something else, but it's not a `TestFailedError`.
What should be the return value? Should the method still throw in spite of the false argument?
Ultimately if the user calls `runner.getAllTestResults` then they would get the exception inside the `TestResultContainer`, but the question is regarding the `eyes.close` itself.
I'm inclined to say that it should throw the exception. The alternative is to return a `TestResultsError` instance, which is something we already use in storybook.
=> Avoid error.getTestResults error

packages/eyes-sdk-core/lib/geometry/Location.js, packages/eyes-sdk-core/lib/geometry/Region.js, packages/eyes-sdk-core/lib/utils/TypeUtils.js, packages/eyes-sdk-core/lib/wrappers/EyesJsExecutor.js, packages/eyes-sdk-core/lib/wrappers/EyesWrappedElement.js, packages/eyes-selenium/package.json, packages/eyes-selenium/src/selenium3/SpecWrappedElement.js, packages/eyes-selenium/src/selenium4/SpecWrappedElement.js, packages/eyes-selenium/test/it/app-with-nodemodules/duplicate-driver.spec.js, packages/eyes-webdriverio-4/src/LegacyWrappedElement.js, packages/sdk-coverage-tests/coverage-tests/custom/DuplicateSdk.spec.js, packages/sdk-coverage-tests/package.json
It seems like the Cucumber testing framework is creating a copy of the SDK's code, and also invalidates require cache. It's not 100% certain, it could be either that or something else - what we do know is that checks for `instanceof` are failing, and when we added console logs for customers that experienced this, the path to the file was the same. Meaning, it's not a duplicate node_module somewhere. It's just loaded again into memory.
This PR serves to fix the particular issue of the customer. After this, we should change all occurences of `instanceof` to `TypeUtils.instanceOf`
In order to do that, we need to add `static get __ConstructorName() { return true; }` to all classes.
We could do this in a utility function, so something like:
```
class Region() {
}
module.exports = …
```
=> Fix duplicate copies of SDK

packages/eyes-sdk-core/lib/useragent/UserAgent.js, packages/eyes-sdk-core/test/unit/useragent/UserAgent.spec.js
[Trello](https://trello.com/c/bOUk7oj8/182-edge-browserstack-user-agent-is-considered-as-chrome)
=> Fix user agent parsing for Edge Chromium

packages/eyes-cypress/src/browser/eyesCheckWindow.js, packages/eyes-cypress/src/plugin/handlers.js, packages/eyes-cypress/test/it/browser/eyesCheckWindow.it.test.js, packages/eyes-cypress/test/unit/plugin/handlers.test.js, packages/eyes-sdk-core/lib/config/Configuration.js, packages/eyes-sdk-core/lib/fluent/DriverCheckSettings.js, packages/eyes-sdk-core/lib/renderer/RenderRequest.js, packages/eyes-sdk-core/test/unit/config/Configuration.spec.js, packages/eyes-sdk-core/test/unit/fluent/CheckSettings.spec.js, packages/eyes-sdk-core/test/unit/renderer/RenderRequest.spec.js, packages/visual-grid-client/src/sdk/checkWindow.js, packages/visual-grid-client/src/sdk/createRenderRequests.js, packages/visual-grid-client/src/sdk/openEyes.js, packages/visual-grid-client/src/sdk/renderingGridClient.js, packages/visual-grid-client/test/it/openEyes.it.test.js, packages/visual-grid-client/test/util/FakeEyesWrapper.js
The point here is to allow a backchannel for the user to configure stuff on the visual grid **without the need to update the SDK**.
This should be possible in various ways - all the ways for the user to specify parameters for check:
1. Classic SDK Configuration
2. Classic SDK CheckSettings
3. Cypress cy.eyesCheckWindow and cy.eyesOpen
4. Storybook applitools.config.js file
So there are quite a few places to add this in the code. Hopefully I covered them all.
The first use case for this is adopted stylesheets. We will use this as a means for the user to specify what to do for browsers that don't support adopted stylesheets (see more in [Trello](https://trello.com/c/cX4q0DzH/390-adoptedstylesheets-feature-not-supported#comment-5f1b44f7530156669ebbe228))
=> Support visualGridOptions

packages/eyes-sdk-core/CHANGELOG.md, packages/eyes-sdk-core/lib/config/Configuration.js, packages/eyes-sdk-core/lib/fluent/DriverCheckSettings.js, packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js, packages/eyes-sdk-core/lib/server/ServerConnector.js, packages/eyes-sdk-core/lib/utils/GeneralUtils.js, packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js, packages/eyes-sdk-core/package.json, packages/eyes-sdk-core/test/unit/config/Configuration.spec.js, packages/eyes-sdk-core/test/unit/fluent/CheckSettings.spec.js, packages/eyes-sdk-core/test/unit/sdk/EyesVisualGrid.spec.js, packages/eyes-sdk-core/test/unit/utils/GeneralUtils.spec.js, packages/sdk-shared/coverage-tests/generic/spec-emitter.js, packages/sdk-shared/coverage-tests/generic/supported-tests.js, packages/sdk-shared/src/render.js, packages/visual-grid-client/CHANGELOG.md, packages/visual-grid-client/package.json, packages/visual-grid-client/src/sdk/checkWindow.js, packages/visual-grid-client/src/sdk/createRenderRequests.js, packages/visual-grid-client/src/sdk/takeScreenshot.js, packages/visual-grid-client/src/visual-grid-client.js, packages/visual-grid-client/test/browser/browser.e2e.test.js, packages/visual-grid-client/test/e2e/openEyes.e2e.test.js, packages/visual-grid-client/test/e2e/render.e2e.test.js, packages/visual-grid-client/test/e2e/takeScreenshot.e2e.test.js, packages/visual-grid-client/test/e2e/testWindow.e2e.test.js, packages/visual-grid-client/test/it/closeEyes.it.test.js, packages/visual-grid-client/test/it/openEyes.it.test.js, packages/visual-grid-client/test/it/testWindow.it.test.js, packages/visual-grid-client/test/unit/sdk/createRenderRequests.test.js
This PR still needs to be finished. I need to fix tests in `visual-grid-client`. But first I would like to know an opinion about the direction I choose.
The idea is to provide an array of snapshots (same as an array of browsers) where each snapshot has the same index as related browser in its array.
=> Add support for layout breakpoints

packages/eyes-sdk-core/lib/config/Configuration.js, packages/eyes-sdk-core/lib/fluent/DriverCheckSettings.js, packages/eyes-sdk-core/lib/sdk/EyesVisualGrid.js, packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js, packages/eyes-sdk-core/test/unit/config/Configuration.spec.js, packages/eyes-sdk-core/test/unit/fluent/CheckSettings.spec.js, packages/sdk-shared/coverage-tests/custom/TestDisableBrowserFetching.spec.js, packages/sdk-shared/coverage-tests/custom/TestVisualGridRefererHeader.spec.js, packages/sdk-shared/coverage-tests/fixtures/ua.html, packages/sdk-shared/coverage-tests/util/ua-middleware.js
This PR adds `disableBrowserFetching` as a configuration parameter to both `Configuration` and `CheckSettings`.
It can serve as a guide to how to add configuration properties.
I was thinking how to test this, and thought it would be best to do an e2e test. Mainly because I wanted to verify that dom-snapshot receives `dontFetchResources`, but it's hard to validate without changing something fundamental: dom-snapshot is run today with no args, so it's hard to test its arguments if they are encoded in the script string. And I didn't want to change it and find myself in a rabbit hole.
So the test I did uses a local test server with a middleware that would serve an image only if it's fetched from Node.js. So I know that DS cannot fetch it and therefore the visual test is an indicator for …
=> Add disableBrowserFetching configuration

packages/eyes-sdk-core/lib/utils/createFramesPaths.js, packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js, packages/eyes-sdk-core/test/it/takeDomSnapshot.spec.js, packages/eyes-sdk-core/test/unit/utils/createFramesPaths.spec.js, packages/sdk-shared/coverage-tests/custom/TestCheckDomSnapshotCrossOriginFrames_VG.spec.js
There are several points here:
1. Be more explicit in tests. Don't try to DRY. Specifying what dom-snapshot returns should be specific to each test, so it should be mocked in each test, rather than in `beforeEach`.
2. Expecting a function to throw: `presult` is a helpful utility when you have an async function that might throw and you want to handle the error.
3. No need for try/catch if catching only throws the error
4. `generateSnapshotObject` is more general and you can specify any overriden property. This leaves room to test also blobs and resourceContents in the future.
5. `should throw an error if timeout is reached` didn't really do anything because it wasn't failing on timeout.
6. `generateSnapshotResponse` has less functionality than the previous `generateSnapshotObject`. If I …
=> takeDomSnapshot.spec.js suggestion

packages/eyes-sdk-core/lib/utils/createFramesPaths.js, packages/eyes-sdk-core/lib/utils/deserializeDomSnapshotResult.js, packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js, packages/eyes-sdk-core/test/it/takeDomSnapshot.spec.js, packages/eyes-sdk-core/test/unit/utils/createFramesPaths.spec.js, packages/eyes-sdk-core/test/utils/MockDriver.js, packages/sdk-shared/coverage-tests/fixtures/cors_frames/cors.hbs, packages/sdk-shared/coverage-tests/fixtures/cors_frames/redirect.hbs
[Trello](https://trello.com/c/iBY0LLki)
Related to https://github.com/applitools/dom-scripts/pull/10
- Fix the try-catch block around the context switching, since it catches and ignores all other errors as well. 
- Insert `data-applitools-src` attribute to each cors frame with a value of `frameSnapshot.url`
=> Override cors frame's src after dom snapshot is taken

packages/eyes-images/index.js, packages/eyes-sdk-core/index.js, packages/eyes-sdk-core/lib/close/BatchClose.js, packages/eyes-sdk-core/lib/close/closeBatch.js, packages/eyes-sdk-core/package.json, packages/eyes-sdk-core/test/unit/close/BatchClose.spec.js, packages/eyes-sdk-core/test/unit/close/closeBatch.spec.js, packages/eyes-sdk-core/yarn.lock
provide the ability to manually close batches using an array of `batchIds`
```
const {BatchClose} = require('@applitools/eyes-sdk-core')
async function someFunction() {
...
await BatchClose().setBatchIds(['123', '456']).close()
...
}
```
you can also provide a custom URL:
```
const {BatchClose} = require('@applitools/eyes-sdk-core')
async function someFunction() {
...
await BatchClose().setUrl('example.com').setBatchIds(['123', '456']).close()
...
}
```
=> feat: batch close

packages/eyes-sdk-core/lib/server/ServerConnector.js, packages/eyes-sdk-core/lib/server/requestHelpers.js, packages/eyes-sdk-core/test/unit/server/ServerConnector.spec.js
For tests blocked by concurrency, the requirement is to have a different backoff than normal failures or polling requests.
The backoff that was decided is 2s x 5, 5s x 4, 10, ....
=> concurrency backoff

packages/eyes-sdk-core/lib/sdk/EyesClassic.js
when using eyes classic with a region and specifying a layout region - the calculation didn't consider the offset of the region - and therefore our layout regions would turn out slightly off their respective positions.
=> fix: correct layout region calculation within a region

.github/workflows/release.yml, packages/eyes-common-legacy/package.json, packages/eyes-cypress/package.json, packages/eyes-images-legacy/package.json, packages/eyes-images/package.json, packages/eyes-leanft/package.json, packages/eyes-nightwatch/package.json, packages/eyes-playwright/package.json, packages/eyes-protractor/package.json, packages/eyes-puppeteer/package.json, packages/eyes-sdk-core-legacy/package.json, packages/eyes-sdk-core/package.json, packages/eyes-selenium-3/package.json, packages/eyes-selenium/package.json, packages/eyes-storybook/package.json, packages/eyes-webdriverio-4-service/package.json, packages/eyes-webdriverio-4/package.json, packages/eyes-webdriverio-5-service/package.json, packages/eyes-webdriverio-5/package.json, packages/sdk-coverage-tests/package.json, packages/sdk-fake-eyes-server/package.json, packages/sdk-release-kit/package.json, packages/sdk-release-kit/src/cli/index.js, packages/sdk-shared/package.json, packages/side-eyes/package.json, packages/snippets/package.json, packages/visual-grid-client/package.json
- temp branch name with timestamp
- grouped stdout
- run `yarn docker:setup` if `use docker` is `true`
- update master with new version
- change `use docker` to `prepublish` and have it be a string - so if you need to run `tsc` instead of `yarn docker:setup` you can just provide it from the action menu.
- update branch temp name to be the **intended** version - this is a bit tricky because we need to know the version prior to running `yarn publish`
- rename to `Publish` as now we can use the same workflow for dev\internal packages as well.
=> chore: use branches and grouped stdout

packages/sdk-release-kit/src/cli/index.js, packages/sdk-release-kit/src/git/index.js, packages/sdk-release-kit/test/git/fixtures/changed.json, packages/sdk-release-kit/test/git/git.spec.js
- include `yarn.lock` in final commit
- run at the very end of the `preversion` and `deps` flow
- doesn't break CI when some files weren't changed (`git add` and `git commit` give out an exit code 1 if the provided files did not change)
=> fix: bongo commit 

.github/workflows/release.yml, packages/eyes-cypress/package.json, packages/eyes-cypress/test/e2e/cypress-run-failed-fetch.test.js, packages/eyes-cypress/test/e2e/cypress-run-helloworld.test.js, packages/eyes-cypress/test/e2e/cypress-run-iframe.test.js, packages/eyes-cypress/test/e2e/cypress-run-multi-browser-version.test.js, packages/eyes-cypress/test/e2e/cypress-run-other.test.js, packages/eyes-cypress/test/e2e/cypress-run-region.test.js, packages/eyes-cypress/test/e2e/cypress-run-simple.test.js, packages/eyes-cypress/test/e2e/pack-install.test.js
- no file linking (`file:../../../../node_modules/cypress`)
- no `ncp` (uses `cp` which creates folder by default if it doesn't exist)
- no parallelization
=> fix: cypress e2e

packages/visual-grid-client/src/sdk/EyesWrapper.js, packages/visual-grid-client/src/sdk/getRenderMethods.js, packages/visual-grid-client/src/sdk/renderingGridClient.js, packages/visual-grid-client/test/it/renderingGridClient.it.test.js, packages/visual-grid-client/test/util/FakeEyesWrapper.js
This is needed for Storybook and Cypress to get device information when layoutBreakpoints is used.
Caching is done inside VGC, and requests are fired lazily.
=> Add API for getting device sizes from VGC

packages/eyes-cypress/src/browser/eyesCheckWindow.js
adding a clause that will check if a given device name exists in the list of devices we got from the server.
there is room for confusion when it comes to device configuration, therefore I added an indicative error message that points to the device list (similar to the readme) and details whether it's an emulated device or iOS.
=> chore(cypress): add device error handling

packages/eyes-cypress/src/browser/commands.js, packages/eyes-cypress/src/plugin/errorDigest.js, packages/eyes-cypress/src/plugin/handlers.js, packages/eyes-cypress/src/plugin/waitForBatch.js, packages/eyes-cypress/test/unit/plugin/errorDigest.test.js, packages/eyes-cypress/test/unit/plugin/handlers.test.js, packages/eyes-cypress/test/unit/plugin/waitForBatch.test.js
we have the ability to get a config property from `cypress` which indicates whether the run is interactive or not, meaning was the test run started with `cypress open` or `cypress run` respectively.
when running in interactive mode - we do not want to format the output with color codes - as it makes the output unreadable.
we could not rely on `process.stdout.isTTY` because it's always `true`.
=> chore(cypress): don't format output when running in interactive mode

packages/eyes-sdk-core/lib/utils/GeneralUtils.js, packages/eyes-sdk-core/lib/utils/takeDomSnapshot.js, packages/eyes-sdk-core/test/it/takeDomSnapshot.spec.js, packages/eyes-sdk-core/test/unit/utils/GeneralUtils.spec.js
when we encounter cross origin frames with the same `src` attribute - the resulting image will have inappropriately positioned iframes and therefore will result in a bad image.
[Trello card](https://trello.com/c/qn5glrAD)
=> fix(takeDomSnapshot): fix CORS frames with same src attribute

packages/eyes-cypress/CHANGELOG.md, packages/eyes-cypress/README.md
added the configuration of the Server url in the environment variables for setting up Applitools in your project
Original PR: #366
=> cypress: fix documentation about setup of Applitools configuration

packages/eyes-testcafe/CHANGELOG.md, packages/eyes-testcafe/src/sdk.js, packages/eyes-testcafe/test/it/legacy-api.spec.js
It seems that after this commit https://github.com/applitools/eyes.sdk.javascript1/commit/772ffef975cd3406cc1f407db55aabcf5990058e the screenshot still turns out viewport when no `target` is specified and no `fully`.
The changes in this PR are complementary to the baseline updates here:
[https://eyes.applitools.com/app/test-results/00000251790254269161/?accountId=UAujt6tHnEKUivQXIz7G6A~~](https://eyes.applitools.com/app/test-results/00000251790254269161/?accountId=UAujt6tHnEKUivQXIz7G6A~~)
=> TestCafe: fix window full page

packages/sdk-coverage-tests/CHANGELOG.md, packages/sdk-coverage-tests/src/report/xml.js, packages/sdk-coverage-tests/test/report.spec.js
This PR switches the order in which we discover what tests to report.
Before this PR we were reading the xunit results file and then mounting more information on each test from the metadata.
Now, we read the metadata and add the `passed` status from the xunit results file.
This means that information about skipped tests is not coming from what happened in runtime, but rather from what was defined during coverage test generation.
=> Include non-emitted tests in coverage tests report

packages/eyes-sdk-core/CHANGELOG.md, packages/eyes-sdk-core/lib/sdk/EyesUtils.js, packages/eyes-sdk-core/test/unit/sdk/EyesUtils.spec.js
- add unit test coverage for EyesUtils.setViewportSize
- improve logging in it, and
- fix bug in its retry logic that prevented the full number of retries and
incorrect error message from bubbling when the window/viewport is unable to
be resized
re: [Trello](https://trello.com/c/xNCZNfPi)
=> core: fix retry in EyesUtils.setViewportSize

packages/eyes-webdriverio-5/src/eyes-service.js
This function does not seem to be in the documentation.
Calling eyesGetTestResults only returns one test, even when you have multiple browsers enabled.
Calling eyesGetAllTestResults when a check failed causes the function to throw, which also prevents me from getting the full list of checks.
=> adding param to eyesGetAllTestResults to not throw when we have errors

packages/sdk-coverage-tests/CHANGELOG.md, packages/sdk-coverage-tests/src/report/xml.js, packages/sdk-coverage-tests/test/report.spec.js
There was a bug when a coverage test is emitted, but it's excluded from the test suite because the framework doesn't support this feature (e.g. native-selectors in Selenium). The bug is that this test is reported as `isSkipped: false` (because it's not emitted to be skipped) but with no test result status (since it was not executed).
This PR fixes the issue by filtering those cases out of the report.
=> Fix bug with unexecuted and unskipped cvg tests

packages/eyes-cypress/CHANGELOG.md, packages/eyes-cypress/src/browser/commands.js, packages/eyes-cypress/src/browser/eyesCheckWindow.js, packages/eyes-cypress/src/browser/getBrowserInfo.js, packages/eyes-cypress/test/it/browser/getBrowserInfo.test.js
[trello](https://trello.com/c/onmEQzNx)
`eyesCheckWindow` was checking for the `name` property of a provided browser configuration.
unfortunately, we (I) also added a default browser name, that explicitly adds the `name` property to any browser configuration.
=> fix(eyes-cypress): validate browser/device configuration

packages/eyes-storybook/CHANGELOG.md, packages/eyes-storybook/README.md
[trello](https://trello.com/c/uja478Dr)
adding `include` documentation with filtering stories example.
=> docs(eyes-storybook): adding include documentation

packages/eyes-cypress/package.json, packages/eyes-cypress/src/plugin/errorDigest.js, packages/eyes-cypress/test/unit/plugin/errorDigest.test.js, packages/eyes-cypress/test/unit/plugin/snapshots/errorDigest.test.json, packages/eyes-cypress/yarn.lock, packages/snaptdout/package.json, packages/snaptdout/yarn.lock
I'm not sure it looks better, but I wanted to point this -
Cypress paints the error in yellow. So anything we don't reset becomes yellow:
WDYT about this change?
=> Reset color in Cypress error message

packages/eyes-images/CHANGELOG.md, packages/eyes-images/lib/Eyes.js, packages/eyes-images/test/unit/Eyes.spec.js
SIDE Eyes uses eyes-images under the hood for classic execution. In this scenario `getScreenshot` is ultimately calling `FullPageCaptureAlgorithm` which was recently changed to return a different object structure ([link](https://github.com/applitools/eyes.sdk.javascript1/commit/6412cea720605cf56c4ff0e4896f6b9350064a47)). This change was not propagated to eyes-images, which causes it to throw. There was no test to surface it which is why it went unnoticed when releasing eyes-images with the change. Currently, this error causes classic execution in SIDE Eyes to break (__in production__). I've confirmed that this patch fixes it.
re: [Trello 822](https://trello.com/c/6oVADkSf)
The error throws inside of the constructor in `eyes-sdk-core/lib/capture/EyesSimpleScreenshot`. Arguably, a better …
=> eyes-images: expose and fix error in getScreenshot

packages/eyes-cypress/CHANGELOG.md, packages/eyes-cypress/src/browser/eyesCheckWindow.js, packages/eyes-cypress/test/e2e/cypress-run-breakpoints.test.js, packages/eyes-cypress/test/fixtures/breakpoints.html, packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/layout-breakpoints.js, packages/sdk-shared/coverage-tests/util/slow-middleware.js
[trello](https://trello.com/c/5Thz1QFs/808-experian-cypress-timeout-when-setlayoutbreakpoint-is-enabled)
while #376 removed eyesTimeout, we notice customers that are hitting the default cypress command timeout (4 seconds) when using js-layouts.
the fix is to set explicit timeout for the `cy.then` that wrap our `takeDomSnapshot` call.
I set it to 900,000 ms which is 15 minutes.
=> fix(eyes-cypress): eyes check window timeout

packages/eyes-storybook/CHANGELOG.md, packages/eyes-storybook/dist/getStories.js, packages/eyes-storybook/src/browser/getStories.js, packages/eyes-storybook/test/fixtures/appWithStorybook/index.js, packages/eyes-storybook/test/it/getStories.it.test.js
Today, when a story has a circular reference in parameters (see below example) we show an error to the console that we ignore parameters for this story.
But there's no need to do this if the circular reference is unrelated to the eyes section of the parameters. We only care about the eyes section.
You could argue that we don't need to return the entire parameters object from the browser at all. That might be right. But it's both a big change in code, and also we don't lose anything from it, and we might want to use it in the future. We just need to not let it fail us.
```
const circular = {param: true}
circular.inner = circular
storiesOf('bla bla', module)
.add('testing circular parameters', () => <div>nothing to see here</div>, {circular, eyes: {include: false}})
```
=> Handle story parameters with circular reference better

packages/eyes-storybook/CHANGELOG.md, packages/eyes-storybook/src/defaultConfig.js, packages/eyes-storybook/src/generateConfig.js, packages/eyes-storybook/src/processResults.js, packages/eyes-storybook/test/fixtures/applitools-legacy-concurrency.config.js, packages/eyes-storybook/test/it/eyesStorybook.it.test.js, packages/eyes-storybook/test/unit/generateConfig.test.js, packages/eyes-storybook/test/util/fakeEyesServer.js
PR #375 created a regression, where `concurrency` parameter was masked by the default value of `testConcurrency`.
The solution is to not have either `concurrency` or `testConcurrency` in the `defaultConfig` object, but rather populate the default dynamically.
There was a burning need to test this e2e. Otherwise there's no assurance that the correct concurrency take effect.
I implemented it in storybook's version of the fake eyes server.
The next steps for this are:
1. Consolidate the value for default testConcurrency into one place (I left `// TODO require from core` comments).
2. Provide this in the fake eyes server that's also outside of storybook (maybe even consolidate the two - we have a technical debt here).
3. Ideally this would be available for generic tests so that they could be …
=> Fix legacy concurrency in Storybook

packages/eyes-sdk-core/CHANGELOG.md, packages/eyes-sdk-core/lib/MatchWindowAndCloseTask.js, packages/eyes-sdk-core/lib/MatchWindowTask.js, packages/eyes-sdk-core/lib/config/Configuration.js, packages/eyes-sdk-core/lib/fluent/CheckSettings.js, packages/eyes-sdk-core/lib/fluent/CheckSettingsUtils.js, packages/eyes-sdk-core/lib/fluent/DriverCheckSettings.js, packages/eyes-sdk-core/lib/match/ImageMatchOptions.js, packages/eyes-sdk-core/test/unit/config/Configuration.spec.js, packages/eyes-sdk-core/test/unit/fluent/CheckSettings.spec.js, packages/eyes-sdk-core/test/unit/fluent/CheckSettingsUtils.spec.js, packages/visual-grid-client/CHANGELOG.md, packages/visual-grid-client/src/sdk/checkWindow.js, packages/visual-grid-client/src/sdk/createCheckSettings.js
This PR adds the following API:
```
configuration.getVariantId()
configuration.setVariantId(variantId)
checkSettings.variantId(variantId)
checkSettings.getVariantId()
```
When set, the value is sent in the `options` field of `MatchWindowData`.
As usual, checkSettings overrides configuration.
Generic tests:
https://github.com/applitools/sdk.coverage.tests/pull/72
=> Support Variant ID

.github/workflows/release.yml
[trello](https://trello.com/c/hL7aN2J2/828-save-coverage-test-results-in-github-actions)
this PR introduces saving the `coverage-test-report.xml` and `coverage-test-metadata.json` files for each release.
this was implemented in `Coverage test a package` action, with default retention.
since we run `release` more often than `Coverage test a package` - we need to decide on the retention period for these release runs.
`retention-days` - defaults to 90 days, if not set.
=> chore(release): save coverage test report

packages/sdk-coverage-tests/CHANGELOG.md, packages/sdk-coverage-tests/src/generate/save.js, packages/sdk-coverage-tests/src/report/xml.js, packages/sdk-coverage-tests/test/report.spec.js
Currently tests with fluent vs. classic API are reported with exactly the same parameters to bongo, causing them to not be counted in the report.
This PR adds `api` entry to the metadata file, then after tests are executed it reads from the metadata file and populates it in the test object in the report.
=> Add api parameter to test object in bongo report

packages/sdk-coverage-tests/CHANGELOG.md, packages/sdk-coverage-tests/src/report/xml.js, packages/sdk-coverage-tests/test/fixtures/multiple-suites-with-custom-tests.xml, packages/sdk-coverage-tests/test/report.spec.js
our coverage report was consistently missing the custom coverage tests.
the `convertJunitXmlToResultSchema` function in `sdk-coverage-tests` used to iterate over the json metadata file, which by definition does not contain any information about custom tests.
with this PR, we are running on *all* test results in the xml file - mapping any generic test to it's own object as before, but this time, including the custom coverage tests as well.
=> fix(sdk-coverage-tests): fixing custom coverage tests in report

packages/eyes-testcafe/CHANGELOG.md, packages/eyes-testcafe/ts/eyes.ts, packages/visual-grid-client/CHANGELOG.md, packages/visual-grid-client/index.d.ts
[trello](https://trello.com/c/B71uljbi)
Warner are using typescript with `testcafe`, and I found a missing type in the eyes open options (in `visual-grid-client`) which caused a type error for the customer.
I also turned `accessibilityValidation` (in `eyes-testcafe`) to optional - since it's not required and will create a type error.
=> fix: add iosVersion optional type

packages/eyes-storybook/CHANGELOG.md, packages/eyes-storybook/src/shouldRenderIE.js, packages/eyes-storybook/src/validateAndPopulateConfig.js, packages/eyes-storybook/test/it/eyesStorybook.it.test.js
in continuation of #421 - we used the enum from core - which has a key of `IE_11` with value of `ie`.
the visual grid knows to accept both `ie` and `ie11`.
with some customers using `ie11` - I have decided to add this support to not break existing tests.
=> fix: adding ie11 as possible ie browser

packages/eyes-cypress/CHANGELOG.md, packages/eyes-cypress/package.json, packages/eyes-cypress/src/browser/commands.js, packages/eyes-cypress/src/plugin/config.js, packages/eyes-cypress/src/plugin/hooks.js, packages/eyes-cypress/src/plugin/pluginExport.js, packages/eyes-cypress/src/plugin/shouldSetGlobalHooks.js, packages/eyes-cypress/test/e2e/cypress-run-global-hooks.js, packages/eyes-cypress/test/fixtures/testApp/package.json, packages/eyes-cypress/test/it/plugin/pluginExport.test.js, packages/eyes-cypress/test/unit/plugin/errorDigest.test.js, packages/eyes-cypress/test/unit/plugin/shouldSetGlobalHooks.test.js
[trello](https://trello.com/c/2tluhwWN)
in #384 we provided a way to use cypress' global hooks which was introduced in version `6.2.0` using a flag - `experimentalRunEvents`.
this PR addresses the fact that this flag is no longer needed in cypress >= `6.7.0`
| version        | mode/flag           | hooks  |
| ------------- |:-------------:| -----:|
| `>=6.2.0`      | `experimentalRunEvents` flag | global |
| `>=6.7.0`      | run mode      |   global |
| any                | interactive mode   | non-global
=> fix(eyes-cypress): remove need for `experimentalRunEvents` flag in later cypress versions

packages/eyes-sdk-core/CHANGELOG.md, packages/eyes-sdk-core/lib/utils/ImageUtils.js, packages/screenshoter/CHANGELOG.md, packages/screenshoter/src/image.js, packages/screenshoter/test/it/image.spec.js
Fix bug when a cropped part of an image was constructed in the application memory and only then converted to a buffer.  [Trello](https://trello.com/c/1tpLxTYh)
I have to fix it also in screenshoter, since implementation was inherited. In screenshoter I also find out that we have suboptimal algorithms for copy and rotate operations, so I have fixed them as well. I placed a test for this fix in screenshoter, since it just was more pleasant and screenshoter is something we want to use in the future.
=> Fix bug in image cropping

packages/eyes-cypress/CHANGELOG.md, packages/eyes-cypress/README.md, packages/eyes-cypress/src/plugin/handlers.js, packages/eyes-cypress/test/it/browser/eyesCheckWindow.it.test.js, packages/eyes-cypress/test/it/plugin/handlers.test.js, packages/eyes-cypress/test/unit/plugin/handlers.test.js
Add the ability to pass variant group id to checkwindow.
[Trello card](https://trello.com/c/kvzABpoR/843-support-variant-id-and-agentrunid)
=> Cypress - support variant group id

packages/eyes-api/CHANGELOG.md, packages/eyes-api/src/input/Configuration.ts, packages/eyes-api/yarn.lock
[trello](https://trello.com/c/5UA5T3uI)
the `Configuration` class in eyes-api had a method `addProperty` which pushed a property to the `properties` array. unfortunately, the `_config` local private variable was initiated as an empty object - without first creating an empty `properties` array.
=> fix(eyes-api): add properties key to config

packages/scripts/CHANGELOG.md, packages/scripts/cli/render.js, packages/scripts/package.json, packages/scripts/yarn.lock, packages/test-utils/CHANGELOG.md, packages/test-utils/src/setup-eyes.js
this PR introduces some changes to `yarn render`, primarily - the ability to run with the `--compare` flag which will run a visual test on a given url - create a baseline using a classic runner, and then run another visual test using the ultrafast grid against that same baseline.
I have added some aliases for the most used options (such as `b` for `browser` and `v` for `vg` etc...)
the `sdk` flag now allows you to provide an sdk name to use in the render.
=> feat(scripts): eyes compare

packages/eyes-sdk-core/CHANGELOG.md, packages/eyes-sdk-core/lib/utils/getBrowserInfo.js, packages/eyes-sdk-core/test/unit/utils/getBrowserInfo.spec.js
[trello](https://trello.com/c/EX9VYn1s)
fixing a situation where customers provide the following browser configuration object:
```javascript
{
deviceName: 'iPhone X',
screenOrientation: 'landscape',
name: 'chrome' 
}
```
we give this example in our documentation (cypress, testcafe, storybook) to illustrate that this is a chrome emulation and not an ios simulation.
=> fix(eyes-sdk-core): browser info

packages/eyes-storybook/CHANGELOG.md, packages/eyes-storybook/src/getIframeUrl.js, packages/eyes-storybook/test/unit/getIframeUrl.test.js
[trello](https://trello.com/c/VG2St3AJ)
storybook urls may end in a `.html` file - which resulted in the `getIframeUrl` function appending `iframe.html` to the url.
so the end result would look like: `https://some-storybook.com/index.html/iframe.html?eyes-storybook=true`
=> fix(eyes-storybook): handle `.html` files in storybook url

packages/eyes-storybook/CHANGELOG.md, packages/eyes-storybook/README.md
[trello](https://trello.com/c/A160yfTX)
this PR adds a warning about `runBefore` and `runAfter` functions - emphasizing side-effects.
=> docs(eyes-storybook): documenting runBefore and runAfter limitations

packages/eyes-storybook/CHANGELOG.md, packages/eyes-storybook/src/eyesStorybook.js
while introducing the `fake IE` feature - we gave the option to opt in by using the flag `fakeIE` in the config.
unfortunately, we still split the config by browser - even if the flag wasn't provided - which creates a situation where the IE execution is separated from the rest of the browsers causing a major performance hit.
=> fix(eyes-storybook): fix config split when no flag provided

packages/eyes-sdk-core/CHANGELOG.md, packages/eyes-sdk-core/lib/config/Configuration.js, packages/eyes-sdk-core/test/unit/config/Configuration.spec.js
When calling `mergeConfig`, we add all the browser environments to the config regardless if the browser env is already there.  This caused unnecessary calls to `createRGridDOMAndGetResourceMapping`.
I added a check to add an environment to the configuration only if it's not already included in the `browserInfo` array.
=> Add browser environment only once

packages/eyes-cypress/.gitignore, packages/eyes-cypress/CHANGELOG.md, packages/eyes-cypress/test/fixtures/breakpoints.html, packages/eyes-cypress/test/fixtures/testApp/applitools.config.js, packages/eyes-cypress/test/fixtures/testApp/cypress/integration-run/layout-breakpoints.js, packages/eyes-cypress/test/fixtures/testAppCopies/.gitignore
Fix `should not hit the cypress default command timeout` to include smurfs image to simulate slow dom snapshot and update tests names
=> fix layout-breakpoint tests in Cypresss

packages/eyes-sdk-core/lib/server/requestHelpers.js, packages/eyes-sdk-core/test/unit/close/closeBatch.spec.js, packages/eyes-sdk-core/test/unit/server/ServerConnector.spec.js, packages/eyes-sdk-core/test/unit/server/requestHelpers.spec.js
This PR will make the SDK present the user with the actual error message that happened on the server.
I'm not sure if the string I construct is the best one (is it really important to present the user with the request name and status code? it's more for troubleshooting...).
But one insight is that both UFG and Eyes server return a message in the body of the response, which should not be ignored.
The tests I added are also a bit controversial, since they are prone to changes on the server (e.g. if we ask the UFG to fix the 500 response to be 400, then we would need to fix the test).
Happy to get feedback on this.
=> Improve request error output

packages/eyes-cypress/src/browser/commands.js
Replaces reference to `this.test` with `Cypress.currentTest` and fixes #710.
=> fix(eyes-cypress): use `Cypress.currentTest` as a fallback to get `testName` (#710)

packages/eyes-storybook/test/e2e/zero-stories-retry.e2e.test.js, packages/eyes-storybook/test/it/eyesStorybook.it.test.js, packages/eyes-storybook/test/util/fakeEyesServer.js
1) Skip zero stories test for now, as the option to load a story after storybook started was removed from storybook API
2) Add a delay option for a render request in `fakeEyesServer`
=> Adjust eyes-storybook tests to align with storybook 6.4

packages/eyes-sdk-core/lib/sdk/EyesBase.js
We have a bug today that important logs from ServerConnector are not written when setting a console logger programmatically. Those logs **do** work when setting the env var `APPLITOOLS_SHOW_LOGS=true`.
So for example `manager.openEyes({driver, config: {logs: {type: 'console'}}})` doesn't log axios interceptors. And neither does:
```
eyes.setLogHandler(new ConsoleLogHandler(true))
```
The fix is one line, and is applied from the call in https://github.com/applitools/eyes.sdk.javascript1/blob/de3cef079ffa58bbcc8922ebba4a55c5994c539f/packages/eyes-sdk-core/lib/new/open-eyes.js#L18
=> Fix ServerConnector logs

packages/eyes-api/src/enums/AndroidDeviceName.ts, packages/eyes-api/src/enums/AndroidVersion.ts, packages/eyes-api/src/index.ts, packages/eyes-api/src/input/Configuration.ts, packages/eyes-api/src/input/RenderInfo.ts, packages/eyes-api/test/unit/enums.spec.ts, packages/types/src/data.ts, pending-changes.yaml
support addMobileDevice in user API
1. I was not sure whether 'visual-grid-client` should be updated as well, for example:
`visual-grid-client/src/sdk/getDeviceInfoFromBrowserConfig.js` (there are more cases in VGC)
2. in `Configuration.ts` line 1054, once replacing the 'any' with proper types: `AndroidVersion | IosVersion` it results an error in line 1060 regarding to `iosVersion` vs. `version` - is there another way to solve this besides what was done? 
3. idea regarding the place the test for this should be added?
I found this `/eyes-api/test/unit/enums.spec.ts` it tests the emulated devices and ios devices sizes, I might add one test here (need to add a new service/api as well) but it will not test 'addMobileDevice'
=> user API addMobileDevice

js/packages/logger/src/handler-file.ts
Creating the logs directory may cause an exception, due to a race condition. The recursive flag makes `mkdirSync` skip folders that already exist
=> fix(logger): ensure directory existence using recursion
