applitools/eyes.sdk.javascript1

eyes.sdk.core/lib/EyesJsBrowserUtils.js, eyes.selenium/lib/Eyes.js, eyes.selenium/test/check/hide-scrollbars-selenium-test.js
Add setScrollRootElement method, to set target element on which hide scroll
=> Add setScrollRootElement method

eyes.sdk.core/lib/server/ServerConnector.js
small additions to logs in ServerConnector
=> Server connector logs

eyes.sdk.core/lib/renderer/RenderStatusResults.js, eyes.sdk.core/package-lock.json, eyes.sdk.core/test/unit/RenderStatusResults.spec.js
The API with the rendering grid is actually `{ deviceSize: { width, height } }` and not `{width, height}` as in #39
=> Change RenderStatusResults to support deviceSize

packages/eyes-sdk-core/lib/EyesBase.js
right now this method always returns undefined
=> return test results from abortIfNotClosed

packages/visual-grid-client/package.json, packages/visual-grid-client/src/sdk/globalState.js, packages/visual-grid-client/test/unit/sdk/globalState.test.js
=> Fix waitForQueuedRenders

packages/eyes-selenium/lib/capture/EyesWebDriverScreenshot.js, packages/eyes-selenium/test/it/CheckFluent.spec.js
Fix a mistake.
Related to this  card https://trello.com/c/m7vRDQyP/207-js4-ignoreregions-not-working
=> fix subregion region

packages/dom-capture/package.json, packages/sdk-release-kit/package.json, packages/sdk-release-kit/src/changelog/index.js, packages/sdk-release-kit/src/cli/index.js, packages/sdk-release-kit/src/send-report/scripts/send-release-notification.js, packages/sdk-release-kit/src/versions/scripts/verify-commits.js, packages/sdk-release-kit/src/versions/scripts/verify-versions.js, yarn.lock
Added script:
```
bongo --verify-commits
```
This runs:
```
git log --oneline ${tagName}..HEAD -- ${pkgPath}
// for example
git log --oneline @applitools/eyes-selenium@4.33.29..HEAD -- /home/bettyboop/dev/eyes.sdk.javascript1/packages/eyes-selenium
```
If there are unreleased commits, then the process fails and the released is blocked.
If there is no tag, a warning is output in yellow and the release continues.
=> Add verify-commits script

packages/eyes-sdk-core/CHANGELOG.md, packages/eyes-sdk-core/lib/EyesJsBrowserUtils.js, packages/eyes-sdk-core/lib/fluent/CheckSettings.js, packages/eyes-webdriverio-5/CHANGELOG.md, packages/eyes-webdriverio-5/scripts/render.js, packages/eyes-webdriverio-5/src/EyesVisualGrid.js, packages/eyes-webdriverio-5/src/fluent/AccessibilityRegionByElement.js, packages/eyes-webdriverio-5/src/fluent/FloatingRegionByElement.js, packages/eyes-webdriverio-5/src/fluent/IgnoreRegionByElement.js, packages/eyes-webdriverio-5/src/fluent/SelectorByElement.js, packages/eyes-webdriverio-5/src/fluent/SelectorByLocator.js, packages/eyes-webdriverio-5/src/fluent/WebdriverioCheckSettings.js, packages/eyes-webdriverio-5/src/wrappers/EyesWebDriver.js, packages/eyes-webdriverio-5/test/TestVisualGridCheckFluent.js, packages/eyes-webdriverio-5/test/it/toPersistedRegions.spec.js
* Added WDIO 5 target regions support for VG eyes
* Fix xpath script in core
* Fix EyesWebElements regsions
* Moved persisted regions calculation to checkSettings (will write comments about this)  
* refactor region tests to use real driver
=> WDIO5 target regions

package.json, packages/eyes-webdriverio-4-service/package.json, packages/eyes-webdriverio-4-service/src/EyesService.js, packages/eyes-webdriverio-4-service/test/app-name.spec.js, packages/eyes-webdriverio-4-service/test/wdio.conf.js
- add to workspaces
- fix circular reference error by implementing `toJSON`
- fix code for getConfiguration
- update to latest version of SDK
=> Fix wdio4 service

packages/visual-grid-client/src/sdk/supportedBrowsers.js
We now support edgechromium-2 in the UFG
=> Support edgechromium-2

packages/eyes-webdriverio-4/package.json, packages/sdk-coverage-tests/package.json, packages/sdk-coverage-tests/src/cli/commands/process-report.js, packages/sdk-coverage-tests/src/report/upload.js, yarn.lock
Need to define env var `AZURE_STORAGE_CONNECTION_STRING` when running `coverage-tests process report`.
Blob container will be organized like so:
`<sdk name>/<sandbox|prod>/<timestamp>-<version>.json`
For example:
`eyes.webdriverio.javascript4/sandbox/2020-08-10-17-10-34-234-sandbox.json`
`eyes.webdriverio.javascript5/prod/2020-08-10-17-10-34-234-5.21.0.json`
=> upload cvg test result data to azure

packages/eyes-cypress/CHANGELOG.md, packages/eyes-cypress/package.json, packages/eyes-cypress/src/browser/eyesCheckWindow.js, packages/eyes-cypress/src/plugin/handlers.js, packages/eyes-cypress/test/it/browser/eyesCheckWindow.it.test.js, packages/eyes-cypress/test/unit/plugin/handlers.test.js, yarn.lock
All tests pass. Just wanted an extra set of eyes on my changes in case there's something I overlooked or misunderstood.
=> Upgrade eyes-cypress to visual-grid-client 15

packages/sdk-shared/coverage-tests/generic/override-tests.js, packages/visual-grid-client/src/sdk/checkWindow.js
support `full-selector` with fully
=> fix: full-selector support

packages/eyes-nightwatch/src/spec-driver.js, packages/eyes-nightwatch/test/nightwatch.conf.js
1. Use docker container for coverage tests
2. Fix issue with frames
=> Nightwatch fix

packages/eyes-sdk-core/CHANGELOG.md, packages/eyes-sdk-core/lib/server/SessionStartInfo.js, packages/eyes-sdk-core/lib/server/requestHelpers.js, packages/eyes-sdk-core/package.json, packages/eyes-sdk-core/test/fixtures/SessionStartInfo_Serialization.json, packages/eyes-sdk-core/test/it/EyesBase.spec.js, packages/eyes-sdk-core/test/unit/server/ServerConnector.spec.js, packages/eyes-sdk-core/test/unit/server/requestHelpers.spec.js, packages/eyes-sdk-core/yarn.lock
Trello https://trello.com/c/ZX8NX2zg/665-gettaskstatus-enhancement
=> Long running tasks enhancement

packages/eyes-sdk-core/lib/capture/FullPageCaptureAlgorithm.js, packages/eyes-sdk-core/lib/sdk/EyesBase.js, packages/eyes-sdk-core/lib/sdk/EyesClassic.js, packages/eyes-sdk-core/lib/sdk/EyesCore.js, packages/eyes-sdk-core/lib/sdk/EyesUtils.js, packages/screenshoter/src/screenshoter.js, packages/screenshoter/src/takeStitchedScreenshot.js, packages/screenshoter/src/takeViewportScreenshot.js, packages/sdk-coverage-tests/CHANGELOG.md, packages/sdk-coverage-tests/src/emitter.js, packages/sdk-coverage-tests/src/generate/tests-loader.js
I focused more on the screenshoter since this should replace everything else in some point. It's funny how good this logic fits there.
=> Redo image location calculation

packages/eyes-sdk-core/test/unit/server/ServerConnector.spec.js
This PR adds testing for axios configuration of `maxBodyLength`, which determines the maximum payload size of requests to Eyes server.
Points to note:
1. Unit tests for ServerConnector work against fake eyes server.
2. I had to find an endpoint that was the easiest to send a large buffer. The natural choice was `matchWindow`, which has 2 variants: (a) sending the screenshot URL after it was uploaded to Azure storage, and (b) sending the actual screenshot as a buffer (deprecated, but still supported). I used method 2, and planted a 50MB buffer inside the `screenshot` field.
3. I chose 50MB because that would determine if ServerConnector behaves properly. Why? Since it's larger than Axios' default, and smaller than the 200MB which we set in ServerConnector. And there's a limit of 100MB in …
=> Test for maxBodyLength

packages/eyes-cypress/src/browser/commands.js, packages/eyes-cypress/src/browser/eyesCheckWindow.js, packages/eyes-cypress/test/it/browser/eyesCheckWindow.it.test.js
I updated the tests to include a delay in the mock of `sendReqeust`. This surfaces the bug
=> fix eyesCheckWindow not returning a promise

packages/eyes-sdk-core/test/it/takeDomSnapshot.spec.js
This change intends to make the tests clearer and more correct in the following aspects:
1. Correct usage of `uniqueUrl` parameter, which actually tests that the arguments are sent correctly, and that the output is used correctly. It is important to return different values with `counter` when needed, and in other cases just return some manipulation of the input arguments, `url` and `query`.
2. Marking frame nodes in the mocked CDT with attributes like `cross-origin-iframe` so that when looking at the expected output it's clear how to connect the mock with the result.
=> Clearer tests for takeDomSnapshot

packages/sdk-release-kit/src/cli/index.js
superseding #317
an updated version including the latest changes to `bongo` and updated `master`
=> chore: updated version of yargs bongo

packages/eyes-sdk-core/CHANGELOG.md, packages/eyes-sdk-core/lib/fluent/CheckSettingsUtils.js, packages/eyes-sdk-core/test/unit/fluent/CheckSettingsUtils.spec.js, packages/eyes-testcafe/test/custom/EnablePatterns.spec.js, packages/eyes-testcafe/test/unit/util.spec.js, packages/sdk-shared/coverage-tests/custom/EnablePatterns.spec.js
re: [Trello](https://trello.com/c/QCK2xDlS)
=> Support enablePatterns in checkSettings when running on VG

packages/eyes-testcafe/CHANGELOG.md, packages/eyes-testcafe/src/api.ts
=> Agent ID for TestCafe is eyes.webdriverio

packages/driver/package.json, packages/driver/yarn.lock
GH action failed to merge back after a successful publish to npm
=> Driver 2022 04 26 15 22

packages/execution-grid-client/package.json, packages/execution-grid-client/src/cli.ts, packages/execution-grid-client/src/parse-body.ts, packages/execution-grid-client/src/proxy-server.ts, packages/execution-grid-client/src/proxy.ts, packages/execution-grid-client/src/queue.ts, packages/execution-grid-client/src/tunnel.ts, packages/execution-grid-client/test/e2e/proxy-server.spec.ts, packages/execution-grid-client/test/it/proxy-server.spec.ts, packages/execution-grid-client/test/it/proxy.spec.ts, packages/execution-grid-client/test/it/queue.spec.ts, packages/execution-grid-client/test/it/tunnel.spec.ts, packages/execution-grid-client/yarn.lock
- change CLI arguments to less confusing
- add queueing logic
- handle aborted connections during a session creation
- replace `http-proxy` lib with a more flexible custom impl
- add proxy support
=> [eg-client] Refactoring and improvements

packages/eyes-sdk-core/lib/server/getTunnelAgentFromProxy.js, packages/eyes-sdk-core/package.json, packages/eyes-sdk-core/test/unit/server/ServerConnector.spec.js, packages/eyes-sdk-core/test/utils/proxyServer.js, packages/eyes-sdk-core/yarn.lock, pending-changes.yaml
[Trello](https://trello.com/c/6PT2JoRM)
=> fix/self-signed certs when using proxy isHttpOnly

.github/workflows/publish-browser-extension.yml, js/packages/core/src/classic/extract-text.ts, js/packages/eyes-browser-extension/package.json, js/packages/eyes-browser-extension/src/background.js, js/packages/eyes-browser-extension/src/loader/snippet-loader.js, js/packages/eyes-browser-extension/test/it/spec-driver.spec.js, js/packages/eyes-browser-extension/test/utils/setup-eyes.js, js/packages/eyes-browser-extension/webpack.config.babel.js, js/packages/eyes-browser-extension/yarn.lock, js/packages/snippets/src/browser/getText.js, js/packages/snippets/src/browser/hits.js
This PR contains 
- fix issues that found in the coverage tests
- enable coverages tests in `gh action`
=> [browser-extension] Coverage tests issues fix 

js/packages/bongo/src/send-report/send-report-util.js, js/packages/sdk-coverage-tests/src/report/send.js, python/ci_scripts/all_tests_report.sh, python/ci_scripts/send_mail.sh, python/tests/functional/eyes_robotframework/test_integration.py, python/tests/functional/pytest_reporting.py, python/tutorials/report.sh
In the upcoming month we are going to update test results server url 
Here are updates for the python and JS SDKs 
@kyryloonufriiev Update need new release for the sdk.coverage.tests package as well.
=> update tests results server url
